In [1]:
import pandas as pd

In [6]:
hidroponia = pd.read_csv('dataset/Hidroponia_original.csv', engine ='python', index_col=0, encoding='latin-1')

In [7]:
hidroponia.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, Brócoli to Cebollín
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pH               15 non-null     object
 1   EC               15 non-null     object
 2   Hortaliza        15 non-null     object
 3   Sistema          15 non-null     object
 4   Duracion_Ciclo   15 non-null     object
dtypes: object(5)
memory usage: 720.0+ bytes

In [8]:
hortaliza_dummy = pd.get_dummies(hidroponia['Hortaliza'],prefix='Hortaliza')
sistema_dummy = pd.get_dummies(hidroponia['Sistema'],prefix='Sistema')

In [9]:
hidropinia = pd.concat([hidroponia,hortaliza_dummy],axis= 1)
hidropinia = pd.concat([hidroponia,sistema_dummy],axis= 1)

In [10]:
hidropinia

,pH,EC,Hortaliza,Sistema,Duracion_Ciclo,Sistema_Aeroponia,Sistema_Goteo,Sistema_NFT
Cultivo,,,,,,,,
Brócoli,6 to 6.8,2.8 to 3.5,Flor,NFT,70-90,0,0,1
Calabacita,6,1.8 to 2.4,Fruto,Goteo,45,0,1,0
Pepino,5 to 5.5,1.7 to 2,Fruto,Goteo,70-80,0,1,0
Pimientos,5.5 to 6,0.8 to 1.8,Fruto,Goteo,65,0,1,0
fresa,6,1.8 to 2.2,Fruto,NFT,120-150,0,0,1
Tomate,6 to 6.5,2 to 4,Fruto,Goteo,110-120,0,1,0
Albahaca,5.5 to 6,1 to 1.6,Hoja,NFT,90,0,0,1
Repollo,6.5 to 7,2.5 to 3,Hoja,NFT,80-100,0,0,1
Apio,6.5,1.8 to 2.4,Hoja,NFT,90-120,0,0,1
Lechuga,6 to 7,1.2 to 1.8,Hoja,NFT,80-90,0,0,1
Perejil,6 to 6.5,1.8 to 2.2,Hoja,NFT,80,0,0,1
Rábano,6 to 7,1.4 to 1.8,Raiz,Aeroponia,60-70,1,0,0
Espinacas,6 to 7,1.8 to 2.3,Hoja,NFT,75,0,0,1
Zanahoria,5.8 to 6.3,1.6 to 2.0,Raiz,Aeroponia,90-100,1,0,0
Cebollín,6.0 to 7.0,1.4 to 1.8,Tallo,NFT,120,0,0,1